###**Ejercicios de práctica NumPy y pandas**

###Crear e inspeccionar arreglos

1.Importar la biblioteca

In [1]:
import numpy as np
print(np.__version__)

2.1.3


2.Del listado al arreglo

In [2]:
precios = np.array([24000, 28000, 22000, 30000, 8000])
print(type(precios).__name__)
print(precios.dtype)

ndarray
int64


3. Los tres atributos

In [3]:
matriz = np.array([[2, 24000],
                   [1, 28000],
                   [3, 22000]])
print(matriz.shape)     # forma
print(matriz.ndim)     # dimensiones
print(matriz.size)     # total de elementos

(3, 2)
2
6


4.Secuencias automáticas

In [4]:
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)
print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64


5.Corrección: falta algo

In [5]:
precios = np.array([24000, 28000, 22000])

###Vectorización y broadcasting

6.Multiplicar dos arreglos

In [6]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])
ingresos = cantidades * precios
print(ingresos)

[48000 28000 66000 60000  8000]


7.El escalar se estira

In [7]:
con_descuento = precios * 0.9
print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64


8.El mismo cálculo, dos formas

In [8]:
# con listas de Python
lista = [24000, 28000, 22000, 30000, 8000]
resultado = []
for p in lista:
    resultado.append(p * 1.19)
# con NumPy, en una sola línea
resultado_np = ___
print(resultado_np)

9.Predicción: lista o arreglo

In [9]:
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])
print(lista * 2)
print(arreglo * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


10.Predicción: formas distintas

In [10]:
a = np.array([2, 1, 3, 2, 1])
b = np.array([10, 20, 30, 40])
print(a * b)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

11.Corrección: el ciclo sobra

In [11]:
ingresos = np.zeros(5)
for i in range(5):
    ingresos[i] = cantidades[i] * precios[i]

12. Primero, último y una porción

In [12]:
print(precios[0])     # el primero
print(precios[-1])     # el último
print(precios[1:4])     # las posiciones 1, 2 y 3

24000
8000
[28000 22000 30000]


13.La máscara booleana

In [13]:
mascara = precios > 20000

print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

[ True  True  True  True False]
[24000 28000 22000 30000]
104000


14.Dos condiciones a la vez

In [14]:
seleccion = precios[(precios > 10000) >= (precios < 29000)]
print(seleccion)

[24000 28000 22000 30000]


15.Etiquetar según una condición

In [15]:
etiquetas = np.where(precios > 25000, "alto", "normal")
print(etiquetas)

['normal' 'alto' 'normal' 'alto' 'normal']


16.Contar y sumar lo filtrado

In [16]:
caros = precios[precios > 20000]
print(caros.size)      # cuántos son
print(caros.sum())    # cuánto suman

4
104000


17.Corrección: el operador equivocado

In [17]:
seleccion = precios[(precios > 10000) and (precios < 29000)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

###Agregar y resumir

18.Las funciones de resumen

In [18]:
ingresos = np.array([48000, 28000, 66000, 60000, 8000])
print(ingresos.sum())    # 210000
print(ingresos.mean())    # 42000.0
print(ingresos.max())    # 66000
print(round(ingresos.std(), 2))

210000
42000.0
66000
21391.59


19.Sumar por columna

In [19]:
matriz = np.array([[48000, 28000],
                   [66000, 60000],
                   [ 8000, 12000]])
print(matriz.sum(axis=0))

[122000 100000]


20.Sumar por fila y en total

In [20]:
print(matriz.sum(axis=1))
print(matriz.sum())

[ 76000 126000  20000]
222000


21.Predicción: el eje que confunde

In [21]:
print(matriz.mean(axis=0))

[40666.66666667 33333.33333333]


###Del arreglo a la tabla

22.Crear e inspeccionar el DataFrame

In [31]:
import pandas as pd

df_ventas = pd.Dataframe(datos_ventas)
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"])

print(df_ventas.shape)          # forma de la tabla
print(df_ventas.head(3))       # primeras tres filas

AttributeError: module 'pandas' has no attribute 'Dataframe'

23.Una columna o varias

In [32]:
una = df_ventas["producto"]
varias = df_ventas [["producto","cantidad"]]

print(type(una).__name__, type(varias).__name__)

NameError: name 'df_ventas' is not defined

24.Predicción: qué hay debajo de una columna

In [24]:
arreglo = df_ventas["cantidad"].to_numpy()
print(type(arreglo).__name__)
print(arreglo.sum())

NameError: name 'df_ventas' is not defined

25.Predicción: el rango que no se comporta igual

In [25]:
print(df_ventas.loc[0:2].shape[0])
print(df_ventas.iloc[0:2].shape[0])

NameError: name 'df_ventas' is not defined

###Filtrar, derivar y agrupar

26.Filtrar con dos condiciones

In [ ]:
mascara = (
    (df_ventas["sede"] == "Centro")
    & (df_ventas["categoria"] == "Almuerzo")
)
seleccion = df_ventas.loc[mascara].copy()

print(seleccion.shape[0], seleccion["cantidad"].sum())

27.Columnas derivadas

In [ ]:
df_ventas["ingreso"] = df_ventas["cantidad"] * df_ventas["precio_unitario"]
df_ventas["costo_total"] = df_ventas["cantidad"] * df_ventas["costo_unitario"]
df_ventas["margen_bruto"] = df_ventas["ingreso"] - df_ventas["costo_total"]

print(df_ventas["ingreso"].sum(), df_ventas["margen_bruto"].sum())

28.Indicadores globales

In [ ]:
ingreso_total = df_ventas["ingreso"].sum()
margen_total = df_ventas["margen_bruto"].sum()
porcentaje_global = ___(margen_total / ingreso_total * 100, 2)
ticket_promedio = round(ingreso_total / ___(df_ventas), 2)
Intermedio
print(porcentaje_global, ticket_promedio)

29.Agrupar por producto

In [ ]:
kpi = (
    df_ventas
    .___("producto")
    .agg(
        ingreso=("ingreso", "sum"),
        margen=("margen_bruto", "sum"),
    )
    .___()
)
Intermedio
kpi["porcentaje_margen"] = (kpi["margen"] / kpi["ingreso"] * 100).round(2)
print(kpi)

30.Reto integrador: el resumen ejecutivo

In [33]:
def resumen_ejecutivo(df):
    ingreso = df["ingreso"].sum()
    margen = df["margen_bruto"].sum()
    return {
        "total_ingresos": ingreso,
        "margen_bruto": margen,
        "porcentaje_margen": round(margen / ingreso * 100, 2),
        "ticket_promedio": round(ingreso / len(df), 2),
    }
print(resumen_ejecutivo(df_ventas))
Avanzado
solo_centro = df_ventas[df_ventas["sede"] == "Centro"].copy()
print(resumen_ejecutivo(solo_centro))

NameError: name 'df_ventas' is not defined